### ISSUE TITLE
[BUG] Getting capacity leads to compilation error

### ISSUE THREAD

**Issue by josef-schroettle** [martinus/svector#45]
**Describe the bug**
When calling capacity() a compilation error in line 214 is generated.
The type 'size't cannot be stored in T (in my case uint8_t)
The line needs to be changed to
m_data[0] = static_cast<T>((s << 1U) | 1U);

**Comment by martinus** [comment]
should be fixed, can you give the latest version a try: https://github.com/martinus/svector/blob/main/include/ankerl/svector.h
