### ISSUE TITLE
[BUG] Compilation error with /W4 /WX

### ISSUE THREAD

**Issue by josef-schroettle** [martinus/svector#46]
**Describe the bug**
C:\Dev\Code\cansystem\refactor\svector.h(288): warning C4456: Deklaration von "storage" blendet vorherige lokale Deklaration aus
C:\Dev\Code\cansystem\refactor\svector.h(279): note: Siehe Deklaration von "storage"
C:\Dev\Code\cansystem\refactor\svector.h(263): note: beim Kompilieren der Klasse Vorlage-Memberfunktion "void ankerl::v1_0_2::svector<uint8_t,7>::realloc(size_t)"
C:\Dev\Code\cansystem\refactor\svector.h(667): note: Siehe Verweis auf die gerade kompilierte Instanziierung "void ankerl::v1_0_2::svector<uint8_t,7>::realloc(size_t)" der Funktions-Vorlage.
CanMessageAlternatives.cpp(19): note: Siehe Verweis auf die gerade kompilierte Klasse Vorlage-Instanziierung "ankerl::v1_0_2::svector<uint8_t,7>".

I hope you can follow the intent, even if German. There is a local variable 'storage' in line 288 which hides an outer 'storage'. This is a warning in /W4 and an error if wanrings are made to errors with /WX

**Comment by martinus** [comment]
Passt schon, ich versteh Deutsch schon ziemlich gut :smile: 
I guess I should add a MSVC build to the CI.

**Comment by josef-schroettle** [comment]
Please also check your unit-test coverage. Template classes/functions are a challenge as functions are only compiled if used. Also template classes need to be tested with different types as they might have different assignment limitations. A good test type is also a class with deleted copy construction and default moves (and the other way around)
Always unit-test with highest warning level and warnings-as-errors. A good option is also /permissive- (which I did not use)

**Comment by martinus** [comment]
I'd say I have pretty good test coverage, it's just I never compiled on Windows. I've added that to the CI now and fixed a few warnings mostly in unit tests.

I'm compiling with ` -Wall -Wextra -Wpedantic` on Linux and ` /W4` with MSVC, and treat all warnings as errors.
