### ISSUE TITLE
I don't see any documentation on how to run the tests

### ISSUE THREAD

**Issue by leek2** [martinus/svector#48]
I downloaded svector, ran cmake, ran make, and that didn't really do anything.

I couldn't find any documentation on how to build and run the tests.  "make test" and "make check" didn't work anyway.  Maube I  missed the documentation? 

**System (please complete the following information):**
RedHal Enterprise Linux 8, g++ 10.3.0, CMake 3.11.4

**Comment by martinus** [comment]
This project builds with meson: https://mesonbuild.com/

You have to run e.g.
```sh
meson setup builddir
cd builddir
meson test
```
